# Generated by Django 6.0.4 on 2026-04-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
