# Generated by Django 6.0.4 on 2026-04-22 05:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_signup',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
